// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOeHZI8TEqtrGE8QsvSo2lFIpgdMawCfU',
    appId: '1:574018102269:web:e700d44ac29f9bebf42f94',
    messagingSenderId: '574018102269',
    projectId: 'first-a08ec',
    authDomain: 'first-a08ec.firebaseapp.com',
    storageBucket: 'first-a08ec.firebasestorage.app',
    measurementId: 'G-633XF7BT00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0v9boHwr3jzrNHYs-SbxvIzpNu2RozzQ',
    appId: '1:574018102269:android:ba2b14433ad411aff42f94',
    messagingSenderId: '574018102269',
    projectId: 'first-a08ec',
    storageBucket: 'first-a08ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPoyLl4ynb4IqRaSC9e2kNgnhp_8w7LF8',
    appId: '1:574018102269:ios:419e0d5c8757eb5af42f94',
    messagingSenderId: '574018102269',
    projectId: 'first-a08ec',
    storageBucket: 'first-a08ec.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPoyLl4ynb4IqRaSC9e2kNgnhp_8w7LF8',
    appId: '1:574018102269:ios:419e0d5c8757eb5af42f94',
    messagingSenderId: '574018102269',
    projectId: 'first-a08ec',
    storageBucket: 'first-a08ec.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOeHZI8TEqtrGE8QsvSo2lFIpgdMawCfU',
    appId: '1:574018102269:web:e39c61e2911fde1bf42f94',
    messagingSenderId: '574018102269',
    projectId: 'first-a08ec',
    authDomain: 'first-a08ec.firebaseapp.com',
    storageBucket: 'first-a08ec.firebasestorage.app',
    measurementId: 'G-5TZR01RM60',
  );
}
